print("-----------------Unpacking in tuple-----------------------")
t = ('ginger','paste','brush')
a,b,c =t
print(a)
print(b)
print(c)
t1 =('toy','brand','gala','fest','suma')
*a,b=t1
print(a)
print(b)
print()
print("-----------------add an item in tuple-----------------------")
t=t+("dream",)
print(t)
print("-----------------Tuple to a string-----------------------")
t=('C','o','o','l','l','e','g','e')
print(t)
str=''.join(t)
print("After converting tuple to string:",str)